# Generated by Django 6.0.5 on 2026-06-06 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRA_app', '0002_remove_coursemodel_teacher_courseassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
